repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      python_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8
      python_version: python3.7