repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      name: black
      entry: black
      language: python
      language_version: python3
      types: [python]