sudo: required
dist: xenial
language: python
python:
    - "3.7"

# [Browsers]
addons:
    chrome: stable
    firefox: latest

# [Installation]
install:
    - sudo ./install_chromedriver.sh
    - sudo ./install_gecko.sh
    - sudo chmod 777 -R /usr/local/bin/geckodriver
    - sudo chmod 777 -R /usr/local/bin/chromedriver
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3
    - source $HOME/.poetry/env
    - poetry install --no-dev

# [RUN]
script:
    - poetry run pytest tests/ --cov=wire -x

after-script:
    codecov