dist: xenial
language: python
python:
    - "3.7"

# [Browsers]
addons:
    chrome: stable
    firefox: latest

# [GUI]
services:
    - xvfb

# [Installation]
install:
    - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3
    - source $HOME/.poetry/env
    - poetry install --no-dev
    - sudo ./install_chromedriver.sh
    - sudo ./install_gecko.sh

# [RUN]
script:
    - poetry run pytest tests/ --cov=wire

after-script:
    codecov